routes/web.php
<?php


Route::view('/','site.index')->name('site');
Route::get('pontos_de_coleta','PontoController@lista')->name('pontos');

Auth::routes();

Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
    Route::view('/','dashboard.index')->name('dashboard.index');

    Route::resource('ponto','PontoController');
});

app/Ponto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ponto extends Model
{
    protected $fillable = [
        'ponto_nome',
        'ponto_responsavel',
        'ponto_telefone',
        'ponto_email',
        'ponto_cep',
        'ponto_rua',
        'ponto_cidade',
        'ponto_bairro',
        'ponto_sobre',
        'ponto_logo'
    ];

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','apelido','telefone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function ponto(){
        return $this->hasMany(Ponto::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PontoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ponto;

class PontoController extends Controller
{
    public function store(Request $request){

        $user = auth()->user();
        $data = $request->all();

        if($request->hasFile('ponto_logo')){
            $data['ponto_logo'] = $request->ponto_logo->store('pontos');
        }

        $user->ponto()->create($data);

        return redirect()->route('dashboard.index');
    }

    public function lista(){

        $data = Ponto::all();
        return view('site.pontos',compact('data'));

    }
}

resources/views/dashboard/index.blade.php
@extends('template.dashboard')


@section('cabecalho')
<!-- Mask -->
<span class="mask bg-gradient-default opacity-8"></span>
    <!-- Header container -->
    <div class="container-fluid d-flex align-items-center">
    <div class="row">
        <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white">{{ auth()->user()->apelido ?? 'Ponto de Coleta'}}</h1>
        <p class="text-white mt-0 mb-5">This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks</p>
        <a href="#form-editar" class="btn btn-neutral">Cadastre seu ponto</a>
        </div>
    </div>
    </div>

@stop


@section('conteudo')
<div class="col-xl-4 order-xl-2">
          <div class="card card-profile">
            <img src="../../assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  <a href="#">
                    <img src="../../assets/img/theme/team-4.jpg" class="rounded-circle">
                  </a>
                </div>
              </div>
            </div>
            <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
              <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-sm btn-info mr-4">Compartilhar</a>
                <a href="#" class="btn btn-sm btn-default float-right">Suporte</a>
              </div>
            </div>
            <div class="card-body pt-0">
              <div class="row">
                <div class="col">
                  <div class="card-profile-stats d-flex justify-content-center">
                    <div>
                      <span class="heading">22</span>
                      <span class="description">Conexões</span>
                    </div>
                    <div>
                      <span class="heading">10</span>
                      <span class="description">Visualizações</span>
                    </div>
                    <div>
                      <span class="heading">89</span>
                      <span class="description">Comentários</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="text-center">
                <h5 class="h3">
                  {{ auth()->user()->name ?? 'Ponto de Coleta'}}<span class="font-weight-light">, 2019</span>
                </h5>
                <div class="h5 font-weight-300">
                  <i class="ni location_pin mr-2"></i>{{ auth()->user()->cidade ?? 'Cidade'}}, {{ auth()->user()->bairro ?? 'Bairro'}}
                </div>
                <div class="h5 mt-4">
                  <i class="ni business_briefcase-24 mr-2"></i>{{ auth()->user()->profissao ?? 'Profissão'}}
                </div>
                <div>
                  <i class="ni education_hat mr-2"></i>University of Computer Science
                </div>
              </div>
            </div>
          </div>
          <!-- Progress track -->
          <div class="card">
            <!-- Card header -->
            <div class="card-header">
              <!-- Title -->
              <h5 class="h3 mb-0">Materiais mais coletados</h5>
            </div>
            <!-- Card body -->
            <div class="card-body">
              <!-- List group -->
              <ul class="list-group list-group-flush list my--3">
                <li class="list-group-item px-0">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <!-- Avatar -->
                      <a href="#" class="avatar rounded-circle">
                        <img alt="Image placeholder" src="../../assets/img/theme/bootstrap.jpg">
                      </a>
                    </div>
                    <div class="col">
                      <h5>Brinquedos</h5>
                      <div class="progress progress-xs mb-0">
                        <div class="progress-bar bg-orange" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item px-0">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <!-- Avatar -->
                      <a href="#" class="avatar rounded-circle">
                        <img alt="Image placeholder" src="../../assets/img/theme/angular.jpg">
                      </a>
                    </div>
                    <div class="col">
                      <h5>Roupas</h5>
                      <div class="progress progress-xs mb-0">
                        <div class="progress-bar bg-green" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;"></div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item px-0">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <!-- Avatar -->
                      <a href="#" class="avatar rounded-circle">
                        <img alt="Image placeholder" src="../../assets/img/theme/sketch.jpg">
                      </a>
                    </div>
                    <div class="col">
                      <h5>Eletronicos</h5>
                      <div class="progress progress-xs mb-0">
                        <div class="progress-bar bg-red" role="progressbar" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100" style="width: 72%;"></div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item px-0">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <!-- Avatar -->
                      <a href="#" class="avatar rounded-circle">
                        <img alt="Image placeholder" src="../../assets/img/theme/react.jpg">
                      </a>
                    </div>
                    <div class="col">
                      <h5>Livros</h5>
                      <div class="progress progress-xs mb-0">
                        <div class="progress-bar bg-teal" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                      </div>
                    </div>
                  </div>
                </li>
                <li class="list-group-item px-0">
                  <div class="row align-items-center">
                    <div class="col-auto">
                      <!-- Avatar -->
                      <a href="#" class="avatar rounded-circle">
                        <img alt="Image placeholder" src="../../assets/img/theme/vue.jpg">
                      </a>
                    </div>
                    <div class="col">
                      <h5>Alimentos</h5>
                      <div class="progress progress-xs mb-0">
                        <div class="progress-bar bg-green" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;"></div>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-xl-8 order-xl-1" id="form-editar">
          <div class="row">
            <div class="col-lg-6">
              <div class="card bg-gradient-info border-0">
                <!-- Card body -->
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0 text-white">Total traffic</h5>
                      <span class="h2 font-weight-bold mb-0 text-white">350,897</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-white text-dark rounded-circle shadow">
                        <i class="ni ni-active-40"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-white mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span class="text-nowrap text-light">Since last month</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="card bg-gradient-danger border-0">
                <!-- Card body -->
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      <h5 class="card-title text-uppercase text-muted mb-0 text-white">Performance</h5>
                      <span class="h2 font-weight-bold mb-0 text-white">49,65%</span>
                    </div>
                    <div class="col-auto">
                      <div class="icon icon-shape bg-white text-dark rounded-circle shadow">
                        <i class="ni ni-spaceship"></i>
                      </div>
                    </div>
                  </div>
                  <p class="mt-3 mb-0 text-sm">
                    <span class="text-white mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span class="text-nowrap text-light">Since last month</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="card">
            <div class="card-header">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Dados do meu Ponto de Coleta</h3>
                </div>
                <div class="col-4 text-right">
                  <!-- <a href="#!" class="btn btn-sm btn-primary">Settings</a> -->
                </div>
              </div>
            </div>
               @include('dashboard.ponto.create-edit')


          </div>
        </div>
@stop

resources/views/dashboard/ponto/create-edit.blade.php
<form action="{{ route('ponto.store') }}" method="POST" enctype="multipart/form-data">
    <div class="card-body">
        @csrf
            <h6 class="heading-small text-muted mb-4">User information</h6>
            <div class="pl-lg-4">
            <div class="row">
                <div class="col-lg-8">
                <div class="form-group">
                    <label class="form-control-label" for="input-username">Qual nome do seu Ponto?</label>
                    <input type="text" id="input-username" name="ponto_nome" class="form-control" placeholder="Use um bom nome">
                </div>
                </div>
                <div class="col-lg-4">
                <div class="form-group">
                    <label class="form-control-label" for="input-email">Responsável pelo ponto</label>
                    <input type="text" id="input-email" name="ponto_responsavel" class="form-control" placeholder="">
                </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                <div class="form-group">
                    <label class="form-control-label" for="input-first-name">Telefone</label>
                    <input type="text" id="telefone" name="ponto_telefone" class="form-control" placeholder="(0DD)0000-0000">
                </div>
                </div>
                <div class="col-lg-6">
                <div class="form-group">
                    <label class="form-control-label" for="input-last-name">Email</label>
                    <input type="email" id="input-last-name" name="ponto_email" class="form-control" placeholder="email@email.com" >
                </div>
                </div>
            </div>
            </div>
            <hr class="my-4" />
            <!-- Address -->
            <h6 class="heading-small text-muted mb-4">Endereço e Localização</h6>
            <div class="pl-lg-4">
            <div class="row">
                <div class="col-lg-3">
                    <div class="form-group">
                        <label class="form-control-label" for="input-country">Cep</label>
                        <input type="text" name="ponto_cep" id="cep" class="form-control" placeholder="CEP">
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                        <label class="form-control-label" for="input-address">Rua/Logradouro</label>
                        <input id="rua" name="ponto_rua" class="form-control" placeholder="endereço completo + numero" value="" type="text">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                <div class="form-group">
                    <label class="form-control-label" for="input-city">Cidade</label>
                    <input type="text" name="ponto_cidade" id="cidade" class="form-control" placeholder="Cidade" value="">
                </div>
                </div>
                <div class="col-lg-6">
                <div class="form-group">
                    <label class="form-control-label" for="input-country">Bairro</label>
                    <input type="text" name="ponto_bairro" id="bairro" class="form-control" placeholder="Bairro" value="">
                </div>
                </div>

            </div>
            </div>
            <hr class="my-4" />
            <!-- Description -->
            <h6 class="heading-small text-muted mb-4">Sobre</h6>
            <div class="pl-lg-4">
            <div class="form-group">
                <label class="form-control-label">Sobre</label>
                <textarea rows="4" name="ponto_sobre" class="form-control" placeholder="A few words about you ...">Fale um pouco do seu ponto</textarea>
            </div>
                <div class="form-group">
                    <label for="form-control-label">Upload Logo</label>
                    <input type="file" name="ponto_logo" class="form-control">
                </div>
            </div>
    </div>
    <!-- card-body -->

    <div class="card-footer text-center">
        <button type="submit" class="btn btn-success">Salvar Dados</button>
    </div>

</form>

@section('js')
<script src="{{ asset('js/viaCep.js') }}"></script>
<script src="{{ asset('js/jquery.mask.min.js') }}"></script>

<script>
        $(document).ready(function(){
            $('#telefone').mask('(000)0000-0000');
            $('#cep').mask('00.000-000');
        })
</script>

@stop

resources/views/site/index.blade.php
@extends('template.site')


@section('principal')

<!-- para trocar a cor do background do banner =['bg-primary','bg-success','bg-warning'] -->
<div class="header bg-success pt-5 pb-7">
      <div class="container">
        <div class="header-body">
          <div class="row align-items-center">
            <div class="col-lg-6">
              <div class="pr-5">
                <h1 class="display-2 text-white font-weight-bold mb-0">Não colecione coisas, colecione momentos</h1>
                <h2 class="display-4 text-white font-weight-light"> Estamos em manuntenção  de forma planejada, estruturada e transparente.
            </p></h2>
                <p class="text-white mt-4"></p>
                <div class="mt-5">
                  <a href="{{route('register') }}" class="btn btn-neutral my-2">Cadastre seu ponto</a>
                  <a href="{{ route('pontos') }}" class="btn btn-default my-2">Colecte algo</a>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="row pt-5">
                <div class="col-md-6">
                  <div class="card">
                    <div class="card-body">
                      <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow mb-4">
                        <i class="ni ni-active-40"></i>
                      </div>
                      <h5 class="h3">Minimalismo</h5>
                      <p>Argon comes with over 70 handcrafted components.</p>
                    </div>
                  </div>
                  <div class="card">
                    <div class="card-body">
                      <div class="icon icon-shape bg-gradient-info text-white rounded-circle shadow mb-4">
                        <i class="ni ni-active-40"></i>
                      </div>
                      <h5 class="h3">Empreededorismo Social</h5>
                      <p>Fully integrated and extendable third-party plugins that you will love.</p>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 pt-lg-5 pt-4">
                  <div class="card mb-4">
                    <div class="card-body">
                      <div class="icon icon-shape bg-gradient-success text-white rounded-circle shadow mb-4">
                        <i class="ni ni-active-40"></i>
                      </div>
                      <h5 class="h3">Economia Circular</h5>
                      <p>From simple to complex, you get a beautiful set of 15+ page examples.</p>
                    </div>
                  </div>
                  <div class="card mb-4">
                    <div class="card-body">
                      <div class="icon icon-shape bg-gradient-warning text-white rounded-circle shadow mb-4">
                        <i class="ni ni-active-40"></i>
                      </div>
                      <h5 class="h3">Design Sustentável</h5>
                      <p>You will love how easy is to to work with Argon.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="separator separator-bottom separator-skew zindex-100">
        <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
      </div>
    </div>

@stop

resources/views/site/pontos.blade.php
@extends('template.site')

@section('principal')
<section class="py-6 pb-9 bg-default">
      <div class="row justify-content-center text-center">
        <div class="col-md-12">
          <h2 class="display-3 text-white">Não colecione coisa, colecione momentos</h2>
            <p class="lead text-white">
                Estamos em manuntenção  de forma planejada, estruturada e transparente.
            </p>
        </div>
      </div>
      <div class="row justify-content-center">
            <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                <div class="form-group mb-0">
                    <div class="input-group input-group-alternative input-group-merge">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-search"></i></span>
                        </div>
                        <input class="form-control" placeholder="Pequise por ex: eletronicos,livros" type="text">
                    </div>
                </div>
                    <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
            </form>
      </div>
    </section>
<section class="section section-lg pt-lg-0 mt--7">
    <div class="container">
        @foreach($data->chunk(3) as $chunk)
            <div class="card-deck mt-5 d-flex">
                @foreach($chunk as $p)
                    <div class="card card-lift--hover shadow border-0">
                        <img class="card-img-top" src="{{ Storage::url($p->ponto_logo)}}" alt="Imagem de capa do card">
                        <div class="card-body">
                            <h5 class="card-title">{{ $p->ponto_nome}}</h5>
                            <p class="card-text">{{$p->ponto_sobre}}</p>
                            <p class="card-text"><small class="text-muted">cadastrado por: {{ $p->user->apelido}}</small></p>
                        </div>
                        <div class="card-footer text-center pull-right">
                            <a href="" class="btn btn-primary btn-sm" data-toggle="tooltip" title="Visualizar"><i class="fas fa-eye"></i></a>
                            <a href="" class="btn btn-danger btn-sm" data-toggle="tooltip" title="Favoritos"><i class="fas fa-heart"></i></a>
                            <a href="" class="btn btn-info btn-sm" data-toggle="tooltip" title="Compartilhar"><i class="fas fa-share"></i></a>
                        </div>
                    </div>
                @endforeach
            </div>
        @endforeach
    </div>
</section>
@endsection

resources/views/template/dashboard.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>Bem vindo ao Ponto de Coleta</title>

  <!-- Favicon -->
  <link rel="icon" href="{{ asset('assets/img/brand/favicon.png') }}" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{{ asset('assets/vendor/nucleo/css/nucleo.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ asset('assets/vendor/@fortawesome/fontawesome-free/css/all.min.css') }}" type="text/css">
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{{ asset('assets/css/argon.min.css?v=1.0.0') }}" type="text/css">
  @yield('css')
</head>

<body>

  @include('template.includes.dashboard.menu')
  <!-- Main content -->
  <div class="main-content" id="panel">
    <!-- Topnav -->
    @include('template.includes.dashboard.nav')
    <!-- Header -->
    <!-- Header -->
    <div class="header pb-6 d-flex align-items-center" style="min-height: 500px; background-image: url(../../assets/img/theme/profile-cover.jpg); background-size: cover; background-position: center top;">
       @yield('cabecalho')
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--6">
      <div class="row">
        @yield('conteudo')
      </div>
      <!-- Footer -->
      <footer class="footer pt-0">
        <div class="row align-items-center justify-content-lg-between">
          <div class="col-lg-6">
            <div class="copyright text-center text-lg-left text-muted">
              &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
              <li class="nav-item">
                <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
              </li>
              <li class="nav-item">
                <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
              </li>
              <li class="nav-item">
                <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
              </li>
              <li class="nav-item">
                <a href="https://www.creative-tim.com/license" class="nav-link" target="_blank">License</a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="../../assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="../../assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="../../assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="../../assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="../../assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
  <script src="../../assets/vendor/lavalamp/js/jquery.lavalamp.min.js"></script>
  <!-- Argon JS -->
  <script src="../../assets/js/argon.min.js?v=1.0.0"></script>
  <!-- Demo JS - remove this in your project -->
  <script src="../../assets/js/demo.min.js"></script>
  <script>
    // Facebook Pixel Code Don't Delete
    ! function(f, b, e, v, n, t, s) {
      if (f.fbq) return;
      n = f.fbq = function() {
        n.callMethod ?
          n.callMethod.apply(n, arguments) : n.queue.push(arguments)
      };
      if (!f._fbq) f._fbq = n;
      n.push = n;
      n.loaded = !0;
      n.version = '2.0';
      n.queue = [];
      t = b.createElement(e);
      t.async = !0;
      t.src = v;
      s = b.getElementsByTagName(e)[0];
      s.parentNode.insertBefore(t, s)
    }(window,
      document, 'script', '//connect.facebook.net/en_US/fbevents.js');

    try {
      fbq('init', '111649226022273');
      fbq('track', "PageView");

    } catch (err) {
      console.log('Facebook Track Error:', err);
    }
  </script>
  <noscript>
    <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=111649226022273&ev=PageView&noscript=1" />
  </noscript>

  @yield('js')
</body>

</html>

resources/views/template/site.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>.:: Ponto de Coleta ::. </title>

  <!-- Favicon -->
  <link rel="icon" href="{{ asset('assets/img/brand/favicon.png') }}" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{{ asset('assets/vendor/nucleo/css/nucleo.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ asset('assets/vendor/@fortawesome/fontawesome-free/css/all.min.css') }}" type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{{ asset('assets/css/argon.min.css?v=1.0.0') }}" type="text/css">

</head>

<body>

  @include('template.includes.site.menu')
  <!-- Main content -->
  <div class="main-content">
    @yield('principal')
  </div>
  <!-- Footer -->
  <footer class="py-5" id="footer-main">
    <div class="container">
      <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
          <div class="copyright text-center text-xl-left text-muted">
            &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
          </div>
        </div>
        <div class="col-xl-6">
          <ul class="nav nav-footer justify-content-center justify-content-xl-end">
            <li class="nav-item">
              <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
            </li>
            <li class="nav-item">
              <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
            </li>
            <li class="nav-item">
              <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
            </li>
            <li class="nav-item">
              <a href="https://www.creative-tim.com/license" class="nav-link" target="_blank">License</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Argon Scripts -->
  <!-- Core -->
  <script src="./assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="./assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="./assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="./assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="./assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>
  <script src="./assets/vendor/lavalamp/js/jquery.lavalamp.min.js"></script>
  <!-- Optional JS -->
  <script src="./assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>
  <!-- Argon JS -->
  <script src="./assets/js/argon.min.js?v=1.0.0"></script>
  <!-- Demo JS - remove this in your project -->
  <script src="./assets/js/demo.min.js"></script>

</body>

</html>